# name: Move Adhoc Hotfix to Archive Directory

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 13 * * *' # Runs every day at 1 PM UTC (8 AM CDT)

# jobs:
#   move-to-archive:
#     name: Move Adhoc Hotfix to Archive Directory
#     permissions:
#       contents: 'write'
#       id-token: 'write'
#     uses: HCACloudDataEngineering/gcp-hin-workflows/.github/workflows/move_to_archive.yaml@main
#     with:
#       move_files_everyday: false # if we set to `true` it will archive all files in adhoc/hotfix files.
#     secrets:
#       GH_TOKEN: ${{ secrets.GH_TOKEN }}
