name: Call ServiceCentral Workflow for Change Ticket Automation

on:
  pull_request:
    types:
      - closed
    branches:
      - prod
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - 'archive/**'
      - 'docs/**'
      - 'environments/**'
      - '.gitignore'

jobs:
  service_central:
    if: github.event.pull_request.merged == true
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: HCACloudDataEngineering/gcp-hin-workflows/.github/workflows/service_central_workflow.yaml@main
    with:
      pr_number: ${{ github.event.number }}
      repository: ${{ github.repository }}
      server_url: ${{ github.server_url }}