name: GCS Sync Reusable Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      gcs_file_path:
        required: true
        type: string
      cf_region:
        required: false
        type: string
        default: 'us-east4'
      cf_project_id:
        required: false
        type: string
        default: 'hca-hin-dev-datagov'
      cf_name:
        required: false
        type: string
        default: 'clinical_policy_tags_cf_centralized'
      enable_gcs_sync:
        required: false
        type: string
        default: 'false'

jobs:
  gcs_sync:
    runs-on: [self-hosted, onprem-k8s-arc, dind, enterprise, lnx-amd64]
    name: GCS Sync
    environment: ${{ inputs.branch || github.ref_name }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCS Sync Composite Action
        uses: HCACloudDataEngineering/gcp-hin-workflows/gcs/gcs_sync@main
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER != '' && vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICEACCOUNT_GITHUB != '' && vars.SERVICEACCOUNT_GITHUB }}
          branch: ${{ inputs.branch }}
          gcs_file_path: ${{ inputs.gcs_file_path }}
          cf_region: ${{ inputs.cf_region }}
          cf_project_id: ${{ inputs.cf_project_id }}
          cf_name: ${{ inputs.cf_name }}
          enable_gcs_sync: ${{ inputs.enable_gcs_sync }}