v_sourcesysnm: claims
v_databasetype: sqlserver
v_database: ClaimsConnectDB
v_port: 1433
v_secret_name: revapp_claims_remits_sql/versions/latest
v_jdbc_class_name: com.microsoft.sqlserver.jdbc.SQLServerDriver
v_jdbc_jar: mssql-jdbc-12.4.0.jre8.jar
v_jdkfile: jre-8u351-linux-x64.tar.gz
v_jdkversion: jre1.8.0_351
v_jdbcbqpytemplate: BigQuery_to_Claims_PythonTemplate.py
v_machine_type: n1-standard-4

claims_batching_sql: Select claim_id,vendor_cid as pas_coid,unit_num,iplan_id as iplan,cast(bill_dt as string) as bill_dt,patient_acct_num,npi,fed_tax_num, edi_837_type, file_link_path_txt as file_path,claim_file_name as file_name, dw_last_update_date_time as processed_date, 'v_currtimestamp' as dw_last_update_date_time  From edwclm.fact_claim Where where_condition~truncate~10000

claims:
  - schedule_interval: None
    start_date: pendulum.datetime(2024, 9, 1, tz=timezone)
    frequency: None
    dag_name_suffix: claims_batch
    done_file: NONE
    has_sensor: 'No'
    sql: [claims_batching_sql]
    tgttablename: [claims_batching]
    trigger_dag_ids: ['dag_postprocesspolling_claims_sqlserver_adhoc_claims_batch']