#source system specific configuration values

v_sourcesysnm: pa
v_databasetype: db2
v_user: dmxdsnp
v_pwd_secret_name: pa_db2_pwd/versions/latest
v_jdbc_class_name: com.ibm.db2.jcc.DB2Driver
v_jdbc_jar: db2jcc4.jar
v_jdkfile: jre-8u351-linux-x64.tar.gz
v_jdkversion: jre1.8.0_351
v_jdbcbqpytemplate: Jdbc_to_BigQuery_PythonTemplate_ra.py
v_machine_type: n1-standard-4
v_audittablename: edwra_ac.audit_control

tblist1: [
 "1~v_db_synonym.brbglx~v_parallon_ra_stage_dataset_name.brbglx_dly~delete_stack~~SELECT 'v_db_synonym' AS STACK, glx.co_id, glx.pat_no, glx.entered_ts, glx.gl_src, glx.gl_proc_type, glx.gl_account, glx.gl_proc_amt, glx.gl_serv_dt, glx.proc_code, glx.gl_source, glx.factor, glx.pat_type, glx.dept, glx.fin_class, glx.gl_adjust_ind, glx.foreign_fac_id, glx.foreign_dept, glx.foreign_pat_type, glx.foreign_gl_com, glx.foreign_fin_class, glx.process_ind, glx.pedate, TRIM(CAST(acc.sub_unit_no AS CHAR(4))) as sub_unit_num, 'v_currtimestamp' AS dw_last_update_date_time FROM v_db_synonym.brbglx AS glx LEFT OUTER JOIN v_db_synonym.brbacc AS acc ON glx.stack = acc.stack AND glx.co_id = acc.co_id AND glx.pat_no = acc.pat_no WHERE date(glx.entered_ts) = date(CURRENT TIMESTAMP) - 1 DAY FOR READ ONLY WITH UR~100000"
 ]

schedule:
  - schedule_interval: 0 9 * * *  #CTDN0608 Step 10
    start_date: pendulum.datetime(2022, 12, 20, tz=timezone)
    frequency: daily
    done_file: db2_ingest_start_pagl_YYYYMMDD.done
    has_sensor: "No"
    tblist: [tblist1]
    truncatetablelist: ['v_parallon_ra_stage_dataset_name.brbglx_dly']
    server: ["dsnprod.es.medcity.net"]
    schema: 
      - name: ["448","DSNP",""]
    dblist: ['A','B','F','G','H','I','J','K','T']
    trigger_dag_ids: ['dag_integrate_pa_core_tables_daily_pagltxn']