name: Terraform Scoping Deployment

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:

jobs:
  tf-scoping-plan:
    name: TF SCOPING PLAN
    uses: hca-ccoe/workflow-templates/.github/workflows/ru_terraform_base.yml@v3
    if: github.event_name == 'pull_request' && github.event.action != 'closed'  || github.event_name == 'workflow_dispatch'
    with:
      env: prod
      tf-workspace: hca-hin-monitoring-parallon-eim-prod
      tf-path: ./terraform/
      tf-plan: true
      tf-apply: false
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      
  tf-scoping-apply:
    name: TF SCOPING APPLY
    uses: hca-ccoe/workflow-templates/.github/workflows/ru_terraform_base.yml@v3
    if: github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref_name == 'prd'
    with:
      env: prod
      tf-workspace: hca-hin-monitoring-parallon-eim-prod
      tf-path: ./terraform/
      tf-plan: false
      tf-apply: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
