project:
  src-project-id: hca-hin-dev-cur-parallon
  tgt-project-id: hca-hin-dev-cur-parallon
  datasets:
    -
      src-dataset: edwpbs_base_views
      tgt-dataset: edwpbs
      tables:
        -
          name: fact_rcom_pars_denial
          exclude-columns: [dw_last_update_date_time]
          order-by: dw_last_update_date_time desc
        -
          name: eis_scenario_dim
          exclude-columns: [dw_last_update_date_time]
          order-by: dw_last_update_date_time desc
        -
          name: ada_patient_level_detail
          exclude-columns: [dw_last_update_date_time]
          order-by: dw_last_update_date_time desc
        -
          name: rpt_ar_ada_detail
          exclude-columns: [dw_last_update_date_time]
          order-by: dw_last_update_date_time desc
result:
  dataset: edwpbs_ac
  table: data_validation_result
remarks: Tested by Merwin DMello on 2023-09-26 05:30