# parallon - environment level variables
# Note the yaml syntax, single space after colonenv:
env:
 v_env_name: dev
 v_curated_conn_id: hca-hin-dev-cur-parallon
 v_lob: edwra

# gcp projects
 v_proc_project_id: hca-hin-dev-proc-parallon
 v_landing_project_id: hca-hin-dev-landing-parallon
 v_curated_project_id: hca-hin-dev-cur-parallon
 v_project_id: hca-hin-dev-proc-parallon
 v_gcpconnid: hca-hin-dev-proc-parallon
 v_bqconnid: hca-hin-dev-cur-parallon
 v_mirroring_project_id: hca-hin-curated-mirroring-td
 v_pub_project_id: hca-hin-dev-cur-pub
 v_ops_project_id: hca-hin-dev-cur-ops
 v_cm_project_id: hca-hin-dev-cur-clinical
 
# gcp secret url
 v_pwd_secrets_url: projects/259073358779/secrets/
 v_kmskeyname: projects/hca-hin-dev-proc-parallon/locations/us/keyRings/hin-keyring-be8242/cryptoKeys/hin-key-be8242
 v_vault_addr: https://vault.app.hca.cloud
 v_vault_namespace: non-prod
 # gcs bucket name does not start with gs:// This v_dag_bucket_name is not used in the code; looks like composer is set to look here by default
 v_dag_bucket_name: us-east4-composerv2-9-6-dev-7a3a67b1-bucket
 v_data_bucket_name: eim-parallon-cs-datamig-dev-0003
 v_data_archive_bucket_name: eim-parallon-cs-datamig-dev-0003
 v_outbound_file_path: edwradata/outboundfiles/
 v_dag_audit_notification_path: sql/dml/audit_notification/

 # big query datasets
 v_parallon_ra_core_dataset_name: edwra
 v_parallon_ra_stage_dataset_name: edwra_staging
 v_parallon_ra_base_views_dataset_name: edwra_base_views
 v_parallon_ra_views_dataset_name: edwra_views
 v_parallon_ra_audit_dataset_name: edwra_ac
 v_bqutil_fns_dataset_name: bqutil_fns
 v_auth_base_views_dataset_name: auth_base_views
 v_clinical_cm_core_dataset_name: edwcm
 v_clinical_cm_base_views_dataset_name: edwcm_base_views
 v_clinical_cm_views_dataset_name: edwcm_views
 v_ops_pf_core_dataset_name: edwpf
 v_ops_pf_base_views_dataset_name: edwpf_base_views
 v_parallon_pbs_base_views_dataset_name: edwpbs_base_views
 v_parallon_pbs_views_dataset_name: edwpbs_views
 v_fs_base_views_dataset_name: edwfs_base_views
 
 # Email list
 v_success_email_list:
 v_failure_email_list:

 #dataflow buckets
 v_gcs_temp_bucket: gs://eim-parallon-cs-datamig-dev-0003/temp
 v_dfstagebucket: gs://eim-parallon-cs-datamig-dev-0003/dfstage
 v_dfjarbucket: gs://eim-parallon-cs-jar-dev-0003/jdbcjars/
 v_srcfilesdir: edwradata/srcfiles/
 v_archivedir: edwradata/srcfilesarchive/
 v_tgtfilesdir: edwradata/outboundfiles/
 v_tmpobjdir: edwradata/tmp/
 v_schemasubdir: schema/edwra/
 v_gcs_outboundfile_bucket: gs://eim-parallon-cs-datamig-dev-0003/edwradata/outboundfiles/
 v_gcs_outboundfile_bucket_name: eim-parallon-cs-datamig-dev-0003
 v_gcs_outboundfile_folder: edwradata/outboundfiles/
 v_file_df_template: FileServer_to_BigQuery_PythonTemplate.py

 v_team_notification_email: merwin.dmello@hcahealthcare.com
 
 #dataflow environment values
 v_region: us-east4
 v_zone: us-east4-a
 v_network: hca-hin-networks-shared-vpc
 v_maxworkers: 8
 v_numworkers: 1
 v_worker_machine_type: n1-highmem-4

 #secrets
 v_secret_name: unix_td_ra_pwd
 v_secret_version: latest

 v_subnetwork: https://www.googleapis.com/compute/v1/projects/hca-hin-networks/regions/us-east4/subnetworks/hin-dev-proc-parallon-dataflow-us-east4
 v_workload_identity_provider: projects/921112839631/locations/global/workloadIdentityPools/eimda-github-pool-dev/providers/eimda-github-provider-dev
 v_serviceaccount_github: eim-da-gh@hca-hin-dev-proc-parallon.iam.gserviceaccount.com
 v_serviceaccountemail: df-eim-da@hca-hin-dev-proc-parallon.iam.gserviceaccount.com
 v_df_atos_serviceaccountemail: df-atos@hca-hin-dev-proc-parallon.iam.gserviceaccount.com
 v_jdbc_jar: gs://eim-clin-pdoc-ccda-dev-0001/jdbcjars/mssql-jdbc-9.2.1.jre8.jar
 v_gcs_jar_bucket: gs://eim-clin-pdoc-ccda-dev-0001/jdbcjars
 #v_runner: DirectRunner
 v_runner: DataflowRunner

 v_linux_server: xrdclqapphin02b.unix.medcity.net
 v_linux_file_path: /opt/tdgcp/edwra/writeback_gcp/
 v_linux_file_path_donefile: /opt/tdgcp/edwra/writeback_gcp/done_file/
 v_linux_user: td_ra
 v_linux_port: 22

 v_audittablename: edwra_ac.audit_control
 # To allow for concurrent runs of new BQ process and old process, certain tables/files have _BQ suffix
 # Change to empty string when turning off legacy process
 # v_bq_suffix: ""
 v_bq_suffix: "_bq"